version: '3.8'

services:
  trafficserver:
    build: ./ats
    container_name: trafficserver
    ports:
      - "9888:8080"  # Порт для входящего трафика
      - "8081:8081"  # Порт для администрирования (если нужно)
    volumes:
      - ./cache:/var/cache/trafficserver
    networks:
      - dmz
      - private
  db:
    image: mysql:8.0
    container_name: wordpress_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress_password
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - private

  # WordPress (PHP + Apache)
  wordpress:
    image: wordpress:latest
    container_name: wordpress_app
    restart: always
    depends_on:
      - db
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress_password
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - ./wordpress_data:/var/www/html
    ports:
      - "8000:80"
    networks:
      - dmz
      - private

  # webserver:
  #   image: php:8.2-apache
  #   container_name: apache-php
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./src:/var/www/html
  #   #  - ./apache-config:/etc/apache2/sites-available
  #   environment:
  #     APACHE_DOCUMENT_ROOT: /var/www/html
  #   networks:
  #     - private
  #   restart: unless-stopped

networks:
  dmz:
    driver: bridge
  private:
    driver: bridge
    internal: true

volumes:
  minio_data:
  db_data:
