version: '3.8'

services:
  trafficserver:
    build: ./ats
    container_name: trafficserver
    ports:
      - "9888:8080"  # Порт для входящего трафика
      - "8081:8081"  # Порт для администрирования (если нужно)
    volumes:
      - ./cache:/var/cache/trafficserver
    networks:
      - dmz
      - private

  web:
    build: ./next-js
    ports:
      - "3000:3000"
    networks:
      - dmz
      - private



networks:
  dmz:
    driver: bridge
  private:
    driver: bridge
    internal: true

volumes:
  minio_data:
  db_data:
