version: '3.8'

services:
  trafficserver:
    build: ./ats
    container_name: trafficserver
    ports:
      - "9888:8080"  # Порт для входящего трафика
      - "8081:8081"  # Порт для администрирования (если нужно)
    volumes:
      - ./cache:/var/cache/trafficserver
    networks:
      - dmz
      - private


  webserver:
    image: php:8.2-apache
    container_name: apache-php
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/html
    #  - ./apache-config:/etc/apache2/sites-available
    environment:
      APACHE_DOCUMENT_ROOT: /var/www/html
    networks:
      - private
    restart: unless-stopped

networks:
  dmz:
    driver: bridge
  private:
    driver: bridge
    internal: true

volumes:
  minio_data:
